import { describe, expect, test } from "@jest/globals";
import { parseMarkdown } from "./markdownUtils";

describe("markdownUtils Comments", () => {
  describe("parseMarkdown", () => {
    test("simple comment", () => {
      const markdown = "### Header\n\n test\n\n<!-- one comment -->\n\n";
      const story = parseMarkdown(markdown);
      expect(story.sections).toEqual([
        {
          heading: "Header",
          id: "header",
          parts: [
            {
              type: "paragraph",
              text: "test",
            },
            {
              type: "comment",
              text: "one comment",
            },
          ],
        },
      ]);
    });
    test("mermaid comment", () => {
      const markdown =
        "### Header\n\n test\n\n<!-- This chart is autogenerated -->\n\n";
      const story = parseMarkdown(markdown);
      expect(story.sections).toEqual([
        {
          heading: "Header",
          id: "header",
          parts: [
            {
              type: "paragraph",
              text: "test",
            },
          ],
        },
      ]);
    });
  });
});
